# Numpy 基礎の基礎

In [1]:
#NumPyを読みこんで np という名前をつける
import numpy as np

In [2]:
a = np.array([[1,2,3,4],
               [2,3,4,5],
               [3,4,5,6]])

$A = \begin{bmatrix}1&2&3&4\\2&3&4&5\\3&4&5&6\end{bmatrix}$という行列 (matrix)

配列名.shape は配列としての型をタプルで保持しているパラメータ

array_name.shape is a parameter that holds the shape of the array as a tuple.

In [3]:
# 行と列数のタプルが返される
a.shape

(3, 4)

In [4]:
# 番地の参照は0から始まります
# 最も左上は0行0列になります
a[0,0]

np.int64(1)

In [5]:
# print文を用いて値のみを出力することもできます
print(a[0][0])

1


In [13]:
# 要素数を指定して値が0の配列を生成できます
b = np.zeros((1,4))
b

array([[0., 0., 0., 0.]])

In [14]:
# numpy.concatenate()で二つの配列を重ねることが出来ます
print(np.concatenate([a,b]))

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [0. 0. 0. 0.]]


In [17]:
# 左辺をdとすることで新たな配列dとしてメモリー内に保存されます
d = np.concatenate([a,b])
print(d)

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [0. 0. 0. 0.]]


In [18]:
# 4行1列の配列を作ります
c = np.zeros((4,1))
print(c)

[[0.]
 [0.]
 [0.]
 [0.]]


In [19]:
# 結合する軸を指定することで横方向にも結合できます
# 二次元配列の場合、axis=0で縦に、axis=1で横に結合されます
e = np.concatenate([d,c], 1)
print(e)

[[1. 2. 3. 4. 0.]
 [2. 3. 4. 5. 0.]
 [3. 4. 5. 6. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
# 配列を部分的に参照することが出来ます。
print(e[1,1])

3.0


In [21]:
# -1は末尾の番地という意味になります
print(e[-1, -1])

0.0


In [22]:
# 範囲を指定した参照も可能です。終わりの番地は一つ前までの番地を参照します。
e[1:3, 0:3]

array([[2., 3., 4.],
       [3., 4., 5.]])

In [23]:
# 最初から切り出したいときは省略することもできます
e[:3, :3]

array([[1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])

In [24]:
# arange の戻り値もnumpy配列です
X = np.arange(25)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
# reshape することで行数と列数を変えることが出来ます
Y = X.reshape(5,5)
Y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])